// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MessageRoot : GPBRootObject
@end

#pragma mark - TextMessage

typedef GPB_ENUM(TextMessage_FieldNumber) {
  TextMessage_FieldNumber_Text = 1,
};

@interface TextMessage : GPBMessage

/** 文字内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *text;

@end

#pragma mark - ImageMessage

typedef GPB_ENUM(ImageMessage_FieldNumber) {
  ImageMessage_FieldNumber_ThumbnailURL = 1,
  ImageMessage_FieldNumber_BigURL = 2,
  ImageMessage_FieldNumber_OriginalURL = 3,
  ImageMessage_FieldNumber_Width = 4,
  ImageMessage_FieldNumber_Height = 5,
  ImageMessage_FieldNumber_Size = 6,
};

@interface ImageMessage : GPBMessage

/** 缩略图的下载url, 400 * 400保持比例 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *thumbnailURL;

/** 大图的下载url， 2000 * 2000保持比例 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bigURL;

/** 原始图的下载url， 原图大小 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *originalURL;

/** 最大图的宽 */
@property(nonatomic, readwrite) int32_t width;

/** 最大图的高 */
@property(nonatomic, readwrite) int32_t height;

/** 文件大小 */
@property(nonatomic, readwrite) int32_t size;

@end

#pragma mark - AudioMessage

typedef GPB_ENUM(AudioMessage_FieldNumber) {
  AudioMessage_FieldNumber_URL = 1,
  AudioMessage_FieldNumber_Seconds = 2,
  AudioMessage_FieldNumber_Size = 3,
};

@interface AudioMessage : GPBMessage

/** 下载录音的url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

/** 录音长度 */
@property(nonatomic, readwrite) int32_t seconds;

/** 文件大小 */
@property(nonatomic, readwrite) int32_t size;

@end

#pragma mark - ProductMessage

typedef GPB_ENUM(ProductMessage_FieldNumber) {
  ProductMessage_FieldNumber_ProductId = 1,
  ProductMessage_FieldNumber_Name = 2,
  ProductMessage_FieldNumber_Price = 3,
  ProductMessage_FieldNumber_ImageURL = 4,
  ProductMessage_FieldNumber_OwnerId = 5,
  ProductMessage_FieldNumber_OwnerName = 6,
  ProductMessage_FieldNumber_ActivityId = 7,
};

@interface ProductMessage : GPBMessage

/** 产品id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *productId;

/** 产品名字 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 产品价格 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *price;

/** 产品的缩略图 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *imageURL;

/** 卖家用户id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ownerId;

/** 卖家名字 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ownerName;

/** 活动id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *activityId;

@end

#pragma mark - ContactMessage

typedef GPB_ENUM(ContactMessage_FieldNumber) {
  ContactMessage_FieldNumber_UserId = 1,
  ContactMessage_FieldNumber_Name = 2,
  ContactMessage_FieldNumber_ThumbnailURL = 3,
};

@interface ContactMessage : GPBMessage

/** 联系人的用户Id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 联系人的名字 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 联系人的头像url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *thumbnailURL;

@end

#pragma mark - CouponMessage

typedef GPB_ENUM(CouponMessage_FieldNumber) {
  CouponMessage_FieldNumber_CouponCode = 1,
  CouponMessage_FieldNumber_ActivityName = 2,
  CouponMessage_FieldNumber_Currency = 3,
  CouponMessage_FieldNumber_Amount = 4,
};

@interface CouponMessage : GPBMessage

/** 优惠券代码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *couponCode;

/** 活动名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *activityName;

/** 币种 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *currency;

/** 优惠券面额 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *amount;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
